### ISSUE TITLE
Not possible to use optional path limiter [-- <path>*]

### ISSUE THREAD

**Issue by denisoliv** [thenigan/git-diffall#28]
I have tried:
git diffall -- path
git diffall -- path*
git diffall --path*

None of these options worked. Please advise if I missunderstood the command or if it is actually an issue.

**Comment by thenigan** [comment]
The features of `git diffall` were integrated into mainline git in v1.7.11 (back in June of 2012).  I recommend reading `git help difftool` and using `git difftool --dir-diff`.

**Comment by thenigan** [comment]
With `git difftool`, the path limiter works like this:

```
$ git version
git version 2.13.1

$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README
	modified:   test/example.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git difftool -d -- test
```
My difftool then only shows the changes to `test/example.txt`.  `README` is ignored.

**Comment by denisoliv** [comment]
Thank you, Tim. 

That is funny. I was using git diffal for a while since I was not familiar with this option for difftool. 

Thank you for the response and for creating the script. It is essencial in my option. Makes all the sense to be integrated in Git.

**Comment by dnsoliv** [comment]
thenigan, 

Is there any version of your diffall script with [-- path *] command implemented? 

I did try difftool, but for some reason sometimes it does not show all modified files. I am working with BeyondCompare as difftool.
