### ISSUE TITLE
Using it!

### ISSUE THREAD

**Issue by antofthy** [thenigan/git-diffall#32]
How do you even use it?

An example would be nice!

**Comment by thenigan** [comment]
You could start with the installation and setup instructions found in the project wiki (https://github.com/thenigan/git-diffall/wiki).

However, it’s worth noting that this feature was integrated into standard git back in 2012 (git version 1.7.11).  Check out the docs for git difftool --dir-diff (https://git-scm.com/docs/git-difftool).

**Comment by antofthy** [comment]
Maybe that should be added to the top level README :-)
Thanks

**Comment by eeintech** [comment]
Definitely should be added to README, had the same question!
